# Generated by Django 2.0.2 on 2018-02-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toDo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist_tab',
            old_name='user',
            new_name='user_id',
        ),
    ]
